(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> dictionary update sequence element #0 has length 1; 2 is required"
p3
sS'layer'
p4
S'/home/python/web2pyLojinha/applications/lojinha/controllers/importMysql.py'
p5
sS'code'
p6
S'def index(): \n    path = request.folder+"static/mysqlImport/m.txt"\n    f = file(path,\'r\')\n\n    linha = f.readline().split(\',\')\n    \n    d = linha[3]\n    d1 = d.split(\' \')[0]\n    d2 = d1.split(\'/\')\n    d3 = "%s-%s-%s %s"%(d2[2],d2[1],d2[0],d.split(\' \')[1]) #data\n    \n    # db.alunos.insert(nome=linha[1])\n    \n    f.close()\n\n\n    return dict("ddd")\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/python/web2pyLojinha/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/python/web2pyLojinha/applications/lojinha/controllers/importMysql.py", line 18, in <module>\n  File "/home/python/web2pyLojinha/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/python/web2pyLojinha/applications/lojinha/controllers/importMysql.py", line 17, in index\n    return dict("ddd")\nValueError: dictionary update sequence element #0 has length 1; 2 is required\n'
p11
s.